DROP TABLE IF EXISTS `live_charging_data`;
CREATE TABLE live_charging_data (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
id_tag VARCHAR(50),
transaction_id INT,
charge_box_id VARCHAR(30),
connector_id int,
charger_qr_code VARCHAR(50),
station_id VARCHAR(20),
station_name VARCHAR(50),
station_mobile VARCHAR(20),
station_invoice VARCHAR(255),
station_latitude VARCHAR(20),
station_longitude VARCHAR(20),
master_id int,
parent_id int,
cpo_id VARCHAR(20),
station_address_one VARCHAR(255),
station_address_two VARCHAR(255),
station_pincode VARCHAR(6),
station_state VARCHAR(50),
station_country VARCHAR(50),
user_name VARCHAR(50),
user_cms_id VARCHAR(20),
user_email VARCHAR(50),
user_mobile_no VARCHAR(15),
user_wallet_amount double,
user_address_one VARCHAR(50),
user_address_two VARCHAR(50),
user_city VARCHAR(25),
user_state VARCHAR(30),
user_country VARCHAR(50),

charging_vehicle_name VARCHAR(75),
charging_vehicle_number VARCHAR(50),
charging_vehicle_model VARCHAR(50),
charging_vehicle_type VARCHAR(50),
charging_VEHICLE_IMG_URL VARCHAR(100),
charging_VEHICLE_HUB_IMAGE longblob,

start_type VARCHAR(25),
stop_reason VARCHAR(30),

start_energy double,
end_energy double,
start_power double,
end_power double,
start_soc double,
end_soc double,
start_voltage double,
end_voltage double,
start_current double,
end_current double,

start_timestamp timestamp(6) ,
stop_timestamp timestamp(6)
);