CREATE TABLE session_billing_details (
                                         id INT AUTO_INCREMENT PRIMARY KEY,
                                         transaction_id INT,
                                         slab_no INT,
                                         cpo_id VARCHAR(10),
                                         station_id VARCHAR(50),
                                         station_name VARCHAR(100),
                                         station_city VARCHAR(50),
                                         station_state VARCHAR(50),
                                         customer_id_tag VARCHAR(100),
                                         customer_wallet_amount DECIMAL(10,2),
                                         charger_id VARCHAR(50),
                                         charger_qr_code VARCHAR(100),
                                         connector_id INT,
                                         start_energy DECIMAL(12,3),
                                         end_energy DECIMAL(12,3),
                                         energy_kwh DECIMAL(10,3),
                                         unit_fare DECIMAL(10,2),
                                         energy_cost_excl_tax DECIMAL(10,2),
                                         cgst_amount DECIMAL(10,2),
                                         sgst_amount DECIMAL(10,2),
                                         igst_amount DECIMAL(10,2),
                                         energy_cost_incl_tax DECIMAL(10,2),
                                         service_fee_per_kwh DECIMAL(10,2),
                                         service_fee_amount DECIMAL(10,2),
                                         session_amount DECIMAL(10,2),
                                         session_total_amount DECIMAL(10,2),
                                         settlement_amount_owner_with_gst_client DECIMAL(10,2),
                                         settlement_amount_owner_non_gst_client DECIMAL(10,2),
                                         total_amount_owner_with_gst DECIMAL(12,2),
                                         total_amount_owner_non_gst DECIMAL(12,2),
                                         session_start_at TIMESTAMP(6),
                                         session_end_at TIMESTAMP(6),
                                         session_status TINYINT(1)
);