CREATE TABLE ev_history.transaction_energy_values (
transaction_id INT NOT NULL,
id_tag VARCHAR(100) NOT NULL,
charge_box_id VARCHAR(50) NOT NULL,
start_energy DOUBLE DEFAULT 0,
tariff_amount DOUBLE DEFAULT 0,
last_energy DOUBLE DEFAULT 0,
wallet_amount DOUBLE DEFAULT 0,
consumed_energy DOUBLE DEFAULT 0,
consumed_amount DOUBLE DEFAULT 0,
total_consumed_amount DOUBLE DEFAULT 0,
start_timestamp DATETIME NOT NULL,
stop_timestamp DATETIME DEFAULT NULL,
is_active_transaction TINYINT(1) DEFAULT 1,
latest_soc DOUBLE DEFAULT 0,
last_power DOUBLE DEFAULT 0,
last_current DOUBLE DEFAULT 0,
last_voltage DOUBLE DEFAULT 0,
last_energy_value DOUBLE DEFAULT 0,
PRIMARY KEY (transaction_id, start_timestamp)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;