
context.path =

db.ip = localhost
db.port = 3306
db.schema = stevedb
db.user = steve
db.password = root


db2.ip = localhost
db2.port = 3306
db2.schema = ev_history
db2.user = steve
db2.password = root

db3.ip = 15.207.37.132
db3.port = 3306
db3.schema = bigtot_cms
db3.user = root
db3.password = oahWgOnL656j



# Credentials for Web interface access
#
auth.user = admin
auth.password = firstcal123

# The header key and value for Web API access using API key authorization.
# Both must be set for Web APIs to be enabled. Otherwise, we will block all calls.
#
webapi.key = STEVE-API-KEY
webapi.value =Tucker

# Jetty configuration
#
server.host = 192.168.29.230
server.gzip.enabled = true

# Jetty HTTP configuration
#
http.enabled = true
http.port = 9081

# Jetty HTTPS configuration
#
https.enabled = false
https.port = 8443

keystore.path =
keystore.password =

# When the WebSocket/Json charge point opens more than one WebSocket connection,
# we need a mechanism/strategy to select one of them for outgoing requests.
# For allowed values see de.rwth.idsg.steve.ocpp.ws.custom.WsSessionSelectStrategyEnum.
#
ws.session.select.strategy = ALWAYS_LAST

# if BootNotification messages arrive (SOAP) or WebSocket connection attempts are made (JSON) from unknown charging
# stations, we reject these charging stations, because stations with these chargeBoxIds were NOT inserted into database
# beforehand. by setting this property to true, this behaviour can be modified to automatically insert unknown
# stations into database and accept their requests.
#
# CAUTION: setting this property to true is very dangerous, because we will accept EVERY BootNotification or WebSocket
# connection attempt from ANY sender as long as the sender knows the URL and sends a valid message.
#
auto.register.unknown.stations = false

### DO NOT MODIFY ###
steve.version = 3.7.0
git.describe = 0f1ad0c-dirty
db.sql.logging = false
db2.sql.logging=false
db3.sql.logging=false
profile = prod
